apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: fastapi-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
    volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: fastapi-pvc
        # env:
        # - name: DATABASE_URL
        #   value: "postgresql://user:password@postgres-service:5432/dbname"
        # - name: REDIS_URL
        #   value: "redis://redis-service:6379/0"