name: Deploy to Minikube (FastAPI Demo)

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker Image
        run: |
          docker build -t fastapi-demo:latest .

      - name: Apply K8s Manifests
        run: |
          kubectl apply -f k8s/
